apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-cpu
  namespace: dev
spec:
  mode: one
  selector:
    labelSelectors:
      "app": "dev"
  stressors: 
    cpu: 
      workers: 1
      load: 100
      options: ["--cpu 2", "--timeout 600", "--hdd 1"]
  duration: "30s"
  scheduler:
    cron: "@every 2m"

