---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-auth
  annotations:
          tekton.dev/git-0: https://gitlab.222.122.67.218.nip.io
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: "tmax@23!!"
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: sa-pipeline-runner
secrets:
    - name: gitlab-auth
