apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone- 
  labels: 
    tekton.dev/task: git-clone
spec:
  serviceAccountName: sa-pipeline-runner
  taskRef:
    name: git-clone
  params: 
    - name: url
      value: http://gitlab.222.122.67.218.nip.io/root/nhdemo.git
    - name: revision
      value: master
  workspaces: 
    - name: output
      emptyDir: {}
      #      persistentVolumeClaim:
      #  claimName: pvc-build-source
