apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-mvn-jib
spec:
  params:
    - name: git-url 
    - name: revision
      default: master
    - name: image-url 
    - name: insecure-registry
      default: "false"
    - name: build-stage
      default: "dev"
  workspaces:
    - name: source 
    - name: gitops 
  tasks:
    - name: generate-id
      taskRef:
        name: generate-build-id
      params:
        - name: base-version
          value: $(params.build-stage)
    - name: clone-sources
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: output
          workspace: source
    - name: build-image
      taskRef:
        name: jib-maven
      runAfter:
        - clone-sources
      params:
        - name: IMAGE
          value: $(params.image-url):$(tasks.generate-id.results.build-id)
        - name: INSECUREREGISTRY
          value: $(params.insecure-registry)
      workspaces:
        - name: source
          workspace: source
    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - build-image
      params:
        - name: argo-app-name
          value: "kb-dev"
        - name: gitops-url
          value: "http://192.168.121.151:30079/scm/kbdev/kb-dev-deployments.git"
        - name: image-url
          value: $(params.image-url)
        - name: build-id
          value: $(tasks.generate-id.results.build-id)
      workspaces:
        - name: gitops
          workspace: gitops
