# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'


Vagrant.configure("2") do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.define "kw01" do |config|
  config.vm.hostname = "kw01"
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.100.101"
  config.vm.provider :libvirt do |v|
    v.memory = 8192
    v.cpus = 4
    end
  end

  config.vm.define "kw02" do |config|
  config.vm.hostname = "kw02"
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.100.201"
  config.vm.provider :libvirt do |v|
    v.memory = 8192
    v.cpus = 4
    end
  end

end
