---
apiVersion: v1
kind: Namespace
metadata:
  name: code-server
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: code-server
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-code-server-kw
  namespace: code-server
spec:
  storageClassName: "nfs-client"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: works
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: code-server
  name: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: code-server
        image: docker.kubeworks.net/code-server:kw
        imagePullPolicy: IfNotPresent
        env:
          - name: TZ
            value: Asia/Seoul
          - name: PASSWORD
            value: "1"
        volumeMounts:
        - name: works
          mountPath: /home/coder/works
        - name: docker-sock-volume
          mountPath: /var/run/docker.sock
      volumes:
        - name: works
          persistentVolumeClaim:
            claimName: pvc-code-server-kw
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  namespace: code-server
  name: code-server
  labels:
    app: code-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: web
  type: ClusterIP
  selector:
    app: code-server
