---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-build-pvc
  namespace: demo-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-cache-pvc
  namespace: demo-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
