---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trino-pvc
  labels:
    app: trino
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  labels:
    app: trino
spec:
  selector:
    matchLabels:
      app: trino
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: trino
    spec:
      containers:
      - image: kubeworks/trino:dev
        name: trino
        ports:
        - containerPort: 8080
          name: trino-web
        volumeMounts:
        - name: trino-pv
          mountPath: /data/trino
      volumes:
        - name: trino-pv
          persistentVolumeClaim:
            claimName: trino-pvc
---
apiVersion: v1
kind: Service
metadata:
 name: trino-svc
spec:
 type: NodePort
 selector:
   app: trino
 ports:
   - name: trino-web
     protocol: TCP
     port: 8080
     nodePort: 30088
 selector:
   app: trino
