apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: kb-build-pipeline-
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
    name: build-mvn-jib
  params:
  - name: revision
    value: master
  - name: insecure-registry
    value: "true"
  - name: git-url
    value: http://bitbucket.kubeworks.net/scm/dev/kw-mvn.git
  - name: image-url
    value: "docker.kubeworks.net/kw-mvn"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-dev-build
  - name: gitops
    emptyDir: {}
