---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dev-build
  namespace: dev-build
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
