---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kb-build
  namespace: build
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
