apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: demo-pipeline-
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
    name: git-to-image
  params:
  - name: revision
    value: master
  - name: git-url
    value: http://192.168.100.101:30079/scm/demo/vue-trello.git
  - name: image-name
    value: "192.168.100.101:30005/kw/vue:demo"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: demo-build-pvc

