apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-gitea-pipeline-listener
spec:
  serviceAccountName: pipeline-trigger-sa
  serviceType: NodePort
  triggers:
    - name: gitea-pipeline-trigger
      bindings:
        - ref: gitea-pipeline-binding
      template:
        ref: gitea-pipeline-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitea-pipeline-binding
spec:
  params:
    - name: gitrevision
      value: $(body.after)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: image-name
      value: $(body.repository.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: gitea-pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: image-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: gitea-build-pipeline-run-
      spec:
        serviceAccountName: demo-service-account
        pipelineRef:
          name: git-to-image
        params:
          - name: image-name
            value: 192.168.100.100:30005/$(tt.params.image-name)
          - name: revision
            value: $(tt.params.gitrevision)
          - name: git-url
            value: $(tt.params.gitrepositoryurl)
        workspaces:
        - name: source
          persistentvolumeclaim:
            claimName: demo-build-pvc
