apiVersion: batch/v1
kind: Job
metadata:
  generateName: dcgmproftester
spec:
  template:
    metadata:
      labels:
        app: nvidia-gpu-test
    spec:
      containers:
      - name: dcgmproftester11
        image: nvidia/samples:dcgmproftester-2.0.10-cuda11.0-ubuntu18.04
        args: ["--no-dcgm-validation", "-t 1004", "-d 30"]  
        resources:
          limits:
            nvidia.com/gpu: 1    
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]  
      restartPolicy: Never
      runtimeClassName: nvidia
