apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: solr-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: solr
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: solr_metrics
      target:
        type: Value
        value: 50000  

    
    