---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitbucket
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.100.100
    path: "/mnt/data/bitbucket"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitbucket-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: bitbucket
