{
 "title": "Logging Dashboard via Loki",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Service",
    "query": "label_values({namespace=~\".+\"}, namespace)"
   },
   {
    "name": "container",
    "label": "container",
    "query": "label_values({namespace=\"$namespace\"}, container)"
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": "label_values({container=\"$container\"}, stream)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", stream=~\"$stream\", container=~\"$container\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", stream=~\"$stream\", container=~\"$container\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", stream=~\"$stream\", container=~\"$container\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  }
 ]
}