{
 "title": "Tekton Pipelines",
 "time": { "from": "2022-03-14T04:41:04.457Z", "to": "2022-03-14T05:53:10.536Z" },
 "templating": {
  "list": [
   {
    "name": "failed_pr",
    "query": {
     "query": "label_values(tekton_pipelines_controller_pipelinerun_duration_seconds{status=\"failed\"}, pipelinerun)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pipeline Runs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(tekton_pipelines_controller_pipelinerun_duration_seconds{status=\"success\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "count(tekton_pipelines_controller_pipelinerun_duration_seconds{status=\"failed\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Pipeline Run Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_pipelinerun_duration_seconds{}",
     "legendFormat": "{{pipelinerun}}"
    }
   ]
  },
  {
   "title": "Failed Pipelineruns",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_pipelinerun_duration_seconds{pipelinerun=\"$failed_pr\"}",
     "legendFormat": "{{pipelinerun}}"
    }
   ]
  },
  {
   "title": "Running Pipelines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "tekton_pipelines_controller_running_pipelineruns_count{}",
     "legendFormat": "pipelines"
    },
    {
     "expr": "tekton_pipelines_controller_running_taskruns_count{}",
     "legendFormat": "tasks"
    }
   ]
  }
 ]
}